name: splash_video
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter_native_splash:
  video_player:
  flutter:
    sdk: flutter


flutter_native_splash:
  image: "assets/flutter_ui_dev_logo.png"
  color: "#f9f9f9"
  image_dark: "assets/flutter_ui_dev_logo_dark.png"
  color_dark: "#000000"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
